import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import api from '../../utils/api';
import Layout from '../../components/Layout';
import LoadingSpinner from '../../components/LoadingSpinner';
import { useAuth } from '../../context/AuthContext';
import {
  Clock,
  Award,
  Calendar,
  CheckCircle2,
  AlertTriangle,
  XCircle,
  FileText,
  Trophy,
  BarChart2,
} from 'lucide-react';

/* ── helpers ────────────────────────────────────────────────────────────── */
const submissionStatusMeta = {
  submitted:      { label: 'Completed',      icon: CheckCircle2,  color: 'text-green-600 dark:text-green-400' },
  auto_submitted: { label: 'Auto-submitted', icon: AlertTriangle, color: 'text-amber-600 dark:text-amber-400' },
  disqualified:   { label: 'Disqualified',   icon: XCircle,       color: 'text-red-600 dark:text-red-400'    },
  in_progress:    { label: 'In Progress',    icon: Clock,         color: 'text-blue-600 dark:text-blue-400'  },
};

const scoreColor = (pct) => {
  if (pct >= 75) return 'text-green-600 dark:text-green-400';
  if (pct >= 50) return 'text-amber-600 dark:text-amber-400';
  return 'text-red-600 dark:text-red-400';
};

const ringColor = (pct) => {
  if (pct >= 75) return '#22c55e';
  if (pct >= 50) return '#f59e0b';
  return '#ef4444';
};

/* ── Print / PDF Report ─────────────────────────────────────────────────── */
const printReport = (sub, userName) => {
  const fmtDate = (d) => (d ? new Date(d).toLocaleString() : '—');
  const pct = sub.percentage ?? 0;
  const status = submissionStatusMeta[sub.status] || { label: sub.status };

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <title>Assessment Report – ${sub.test?.title || 'Test'}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Segoe UI', Arial, sans-serif; color: #111; background: #fff; padding: 40px; }
    h1 { font-size: 24px; color: #4f46e5; margin-bottom: 4px; }
    .sub { font-size: 13px; color: #666; margin-bottom: 28px; }
    .section { margin-bottom: 24px; }
    .section h2 { font-size: 15px; font-weight: 700; border-bottom: 2px solid #e5e7eb;
                  padding-bottom: 6px; margin-bottom: 12px; color: #374151; }
    table { width: 100%; border-collapse: collapse; font-size: 14px; }
    td, th { padding: 10px 14px; text-align: left; border: 1px solid #e5e7eb; }
    th { background: #f3f4f6; font-weight: 600; }
    .score-big { font-size: 36px; font-weight: 800; color: #4f46e5; }
    .pct { font-size: 18px; color: #6b7280; }
    .bar-wrap { background: #e5e7eb; border-radius: 99px; height: 10px; margin-top: 6px; }
    .bar { height: 10px; border-radius: 99px;
           background: ${pct >= 75 ? '#22c55e' : pct >= 50 ? '#f59e0b' : '#ef4444'};
           width: ${Math.min(pct, 100)}%; }
    .footer { margin-top: 40px; font-size: 11px; color: #9ca3af; text-align: center;
              border-top: 1px solid #e5e7eb; padding-top: 14px; }
    @media print { body { padding: 20px; } }
  </style>
</head>
<body>
  <h1>Assessment Report</h1>
  <div class="sub">Generated on ${fmtDate(new Date())} &nbsp;|&nbsp; Candidate: ${userName || '—'}</div>

  <div class="section">
    <h2>Test Details</h2>
    <table>
      <tr><th>Test Title</th><td>${sub.test?.title || '—'}</td></tr>
      <tr><th>Status</th><td>${status.label}</td></tr>
      <tr><th>Submitted At</th><td>${fmtDate(sub.submittedAt)}</td></tr>
      <tr><th>Time Taken</th><td>${sub.timeTakenMinutes != null ? sub.timeTakenMinutes + ' min' : '—'}</td></tr>
      ${sub.rank ? `<tr><th>Rank</th><td>#${sub.rank}</td></tr>` : ''}
    </table>
  </div>

  <div class="section">
    <h2>Score Summary</h2>
    <div style="text-align:center; padding: 20px 0;">
      <div class="score-big">${sub.totalScore ?? 0} / ${sub.maxScore ?? 0}</div>
      <div class="pct">${pct}%</div>
      <div class="bar-wrap" style="max-width: 300px; margin: 10px auto 0;">
        <div class="bar"></div>
      </div>
    </div>
    <table style="margin-top: 12px;">
      <tr><th>MCQ Score</th><td>${sub.mcqScore ?? 0}</td></tr>
      <tr><th>Coding Score</th><td>${sub.codingScore ?? 0}</td></tr>
      <tr><th>Total Score</th><td>${sub.totalScore ?? 0} / ${sub.maxScore ?? 0}</td></tr>
      <tr><th>Percentage</th><td>${pct}%</td></tr>
    </table>
  </div>

  <div class="footer">This report is auto-generated by the Assessment Portal. For queries, contact your administrator.</div>
</body>
</html>`;

  const win = window.open('', '_blank');
  win.document.write(html);
  win.document.close();
  win.focus();
  setTimeout(() => win.print(), 400);
};

/* ── History Card ───────────────────────────────────────────────────────── */
const HistoryCard = ({ sub, userName }) => {
  const meta = submissionStatusMeta[sub.status] || { label: sub.status, icon: Clock, color: 'text-gray-500' };
  const Icon = meta.icon;
  const pct = sub.percentage ?? 0;

  return (
    <div className="card flex flex-col md:flex-row md:items-center gap-5 hover:shadow-md transition-shadow">
      {/* Score ring */}
      <div
        className="flex-shrink-0 flex flex-col items-center justify-center w-20 h-20 rounded-full border-4 mx-auto md:mx-0"
        style={{ borderColor: ringColor(pct) }}
      >
        <span className={`text-xl font-bold ${scoreColor(pct)}`}>{pct}%</span>
      </div>

      {/* Info */}
      <div className="flex-1 min-w-0">
        <div className="flex flex-wrap items-center gap-2 mb-1">
          <h3 className="font-semibold text-base truncate">{sub.test?.title || 'Untitled Test'}</h3>
          <span className={`flex items-center gap-1 text-xs font-medium ${meta.color}`}>
            <Icon className="w-3.5 h-3.5" />{meta.label}
          </span>
        </div>
        <div className="flex flex-wrap gap-x-4 gap-y-1 text-sm text-gray-500">
          <span className="flex items-center gap-1">
            <Award className="w-3.5 h-3.5" />
            {sub.totalScore ?? 0}/{sub.maxScore ?? 0} marks
          </span>
          <span className="flex items-center gap-1">
            <FileText className="w-3.5 h-3.5" />
            MCQ: {sub.mcqScore ?? 0} &nbsp;|&nbsp; Coding: {sub.codingScore ?? 0}
          </span>
          {sub.rank && (
            <span className="flex items-center gap-1">
              <Trophy className="w-3.5 h-3.5 text-yellow-500" />Rank #{sub.rank}
            </span>
          )}
          {sub.submittedAt && (
            <span className="flex items-center gap-1">
              <Calendar className="w-3.5 h-3.5" />
              {new Date(sub.submittedAt).toLocaleDateString(undefined, {
                day: '2-digit', month: 'short', year: 'numeric',
              })}
            </span>
          )}
          {sub.timeTakenMinutes != null && (
            <span className="flex items-center gap-1">
              <Clock className="w-3.5 h-3.5" />{sub.timeTakenMinutes} min
            </span>
          )}
        </div>
      </div>

      {/* Actions */}
      <div className="flex gap-2 shrink-0 flex-wrap justify-end">
        {['submitted', 'auto_submitted'].includes(sub.status) && (
          <Link
            to={`/tests/${sub.test?._id}/result`}
            className="btn-secondary px-3 py-2 text-sm flex items-center gap-1"
          >
            <BarChart2 className="w-4 h-4" /> View Result
          </Link>
        )}
        {['submitted', 'auto_submitted', 'disqualified'].includes(sub.status) && (
          <button
            onClick={() => printReport(sub, userName)}
            className="btn-primary px-3 py-2 text-sm flex items-center gap-1"
          >
            <FileText className="w-4 h-4" /> Download Report
          </button>
        )}
      </div>
    </div>
  );
};

/* ── Main Component ─────────────────────────────────────────────────────── */
const CandidateDashboard = () => {
  const { user } = useAuth();
  const [history, setHistory] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    api
      .get('/submissions/my')
      .then((res) => setHistory(res.data.data || []))
      .catch(() => {})
      .finally(() => setLoading(false));
  }, []);

  const completedHistory = history.filter((s) =>
    ['submitted', 'auto_submitted', 'disqualified'].includes(s.status)
  );

  return (
    <Layout>
      <div className="space-y-6">
        {/* Welcome banner with stats */}
        <div className="card bg-gradient-to-r from-primary-600 to-indigo-600 text-white">
          <h1 className="text-2xl font-bold">My Dashboard</h1>
          <p className="text-primary-100 mt-1">Here's a summary of all your assessments.</p>
          {completedHistory.length > 0 && (
            <div className="flex flex-wrap gap-8 mt-5">
              <div>
                <p className="text-3xl font-bold">{completedHistory.length}</p>
                <p className="text-primary-200 text-sm">Tests Completed</p>
              </div>
              <div>
                <p className="text-3xl font-bold">
                  {Math.round(
                    completedHistory.reduce((s, r) => s + (r.percentage || 0), 0) /
                      completedHistory.length
                  )}%
                </p>
                <p className="text-primary-200 text-sm">Avg. Score</p>
              </div>
              <div>
                <p className="text-3xl font-bold">
                  {Math.max(...completedHistory.map((r) => r.percentage || 0))}%
                </p>
                <p className="text-primary-200 text-sm">Best Score</p>
              </div>
            </div>
          )}
        </div>

        {/* ── Test History ── */}
        <div className="flex items-center justify-between">
          <h2 className="text-xl font-semibold">
            Test History
            {completedHistory.length > 0 && (
              <span className="ml-2 text-sm font-normal bg-primary-100 dark:bg-primary-900/40 text-primary-700 dark:text-primary-300 px-2 py-0.5 rounded-full">
                {completedHistory.length}
              </span>
            )}
          </h2>
        </div>

        {loading ? (
          <LoadingSpinner />
        ) : completedHistory.length === 0 ? (
          <div className="card text-center py-14 text-gray-500 space-y-2">
            <Award className="w-12 h-12 mx-auto text-gray-300 dark:text-gray-600" />
            <p className="font-medium">No completed tests yet.</p>
            <p className="text-sm">Your results will appear here once you submit a test.</p>
          </div>
        ) : (
          <div className="grid gap-4">
            {completedHistory.map((sub) => (
              <HistoryCard key={sub._id} sub={sub} userName={user?.name} />
            ))}
          </div>
        )}
      </div>
    </Layout>
  );
};

export default CandidateDashboard;
