import { useEffect, useState } from 'react';
import { useParams, Link, useLocation } from 'react-router-dom';
import api from '../../utils/api';
import Layout from '../../components/Layout';
import LoadingSpinner from '../../components/LoadingSpinner';
import { Award, Trophy, ArrowLeft, FileText, CheckCircle2, XCircle } from 'lucide-react';
import { useAuth } from '../../context/AuthContext';

/* ── Print / PDF Report ─────────────────────────────────────────────────── */
const printReport = (result, userName) => {
  if (!result) return;
  const fmtDate = (d) => (d ? new Date(d).toLocaleString() : '—');
  const pct = result.percentage ?? 0;

  const codingRows = (result.codingAnswers || [])
    .map(
      (ca, i) => `
    <tr>
      <td>Question ${i + 1}</td>
      <td>${ca.score ?? 0} / ${ca.maxScore ?? 0}</td>
      <td>${ca.language || '—'}</td>
      <td>${ca.evalStatus || '—'}</td>
      ${ca.plagiarismScore > 50 ? `<td style="color:#ef4444">⚠ ${ca.plagiarismScore}% similarity</td>` : '<td>—</td>'}
    </tr>`
    )
    .join('');

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <title>Assessment Report – ${result.test?.title || 'Test'}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Segoe UI', Arial, sans-serif; color: #111; background: #fff; padding: 40px; }
    h1 { font-size: 24px; color: #4f46e5; margin-bottom: 4px; }
    .sub { font-size: 13px; color: #666; margin-bottom: 28px; }
    .section { margin-bottom: 24px; }
    .section h2 { font-size: 15px; font-weight: 700; border-bottom: 2px solid #e5e7eb;
                  padding-bottom: 6px; margin-bottom: 12px; color: #374151; }
    table { width: 100%; border-collapse: collapse; font-size: 14px; }
    td, th { padding: 10px 14px; text-align: left; border: 1px solid #e5e7eb; }
    th { background: #f3f4f6; font-weight: 600; }
    .score-big { font-size: 40px; font-weight: 800; color: #4f46e5; }
    .pct { font-size: 20px; color: #6b7280; }
    .bar-wrap { background: #e5e7eb; border-radius: 99px; height: 12px; margin-top: 8px; }
    .bar { height: 12px; border-radius: 99px;
           background: ${pct >= 75 ? '#22c55e' : pct >= 50 ? '#f59e0b' : '#ef4444'};
           width: ${Math.min(pct, 100)}%; }
    .footer { margin-top: 40px; font-size: 11px; color: #9ca3af; text-align: center;
              border-top: 1px solid #e5e7eb; padding-top: 14px; }
    @media print { body { padding: 20px; } }
  </style>
</head>
<body>
  <h1>Assessment Report</h1>
  <div class="sub">Generated on ${fmtDate(new Date())} &nbsp;|&nbsp; Candidate: ${userName || '—'}</div>

  <div class="section">
    <h2>Test Details</h2>
    <table>
      <tr><th>Test Title</th><td>${result.test?.title || '—'}</td></tr>
      <tr><th>Status</th><td>${result.status || '—'}</td></tr>
      <tr><th>Submitted At</th><td>${fmtDate(result.submittedAt)}</td></tr>
      ${result.rank ? `<tr><th>Rank</th><td>#${result.rank}</td></tr>` : ''}
    </table>
  </div>

  <div class="section">
    <h2>Score Summary</h2>
    <div style="text-align:center; padding: 20px 0;">
      <div class="score-big">${result.totalScore ?? 0} / ${result.maxScore ?? 0}</div>
      <div class="pct">${pct}%</div>
      <div class="bar-wrap" style="max-width: 320px; margin: 10px auto 0;">
        <div class="bar"></div>
      </div>
    </div>
    <table style="margin-top:16px;">
      <tr><th>MCQ Score</th><td>${result.mcqScore ?? 0}</td></tr>
      <tr><th>Coding Score</th><td>${result.codingScore ?? 0}</td></tr>
      <tr><th>Total Score</th><td>${result.totalScore ?? 0} / ${result.maxScore ?? 0}</td></tr>
      <tr><th>Percentage</th><td>${pct}%</td></tr>
    </table>
  </div>

  ${
    (result.codingAnswers || []).length > 0
      ? `<div class="section">
    <h2>Coding Submissions</h2>
    <table>
      <thead><tr><th>Question</th><th>Score</th><th>Language</th><th>Eval Status</th><th>Plagiarism</th></tr></thead>
      <tbody>${codingRows}</tbody>
    </table>
  </div>`
      : ''
  }

  <div class="footer">This report is auto-generated by the Assessment Portal. For queries, contact your administrator.</div>
</body>
</html>`;

  const win = window.open('', '_blank');
  win.document.write(html);
  win.document.close();
  win.focus();
  setTimeout(() => win.print(), 400);
};

/* ── Component ──────────────────────────────────────────────────────────── */
const TestResult = () => {
  const { testId } = useParams();
  const location = useLocation();
  const { user } = useAuth();
  const [result, setResult] = useState(location.state?.result || null);
  const [loading, setLoading] = useState(!result);

  useEffect(() => {
    if (!result) {
      api
        .get(`/submissions/${testId}/result`)
        .then((res) => setResult(res.data.data))
        .finally(() => setLoading(false));
    }
  }, [testId, result]);

  if (loading) return <Layout><LoadingSpinner /></Layout>;

  const pct = result?.percentage ?? 0;
  const scoreBarColor =
    pct >= 75 ? 'bg-green-500' : pct >= 50 ? 'bg-amber-500' : 'bg-red-500';

  return (
    <Layout>
      <div className="max-w-2xl mx-auto space-y-6">
        {/* Back + Download */}
        <div className="flex items-center justify-between gap-4 flex-wrap">
          <Link to="/dashboard" className="flex items-center gap-2 text-primary-600 hover:underline">
            <ArrowLeft className="w-4 h-4" /> Back to Dashboard
          </Link>
          {result && (
            <button
              onClick={() => printReport(result, user?.name)}
              className="btn-primary flex items-center gap-2"
            >
              <FileText className="w-4 h-4" /> Download Report (PDF)
            </button>
          )}
        </div>

        <div className="card text-center">
          <div className="w-20 h-20 bg-primary-100 dark:bg-primary-900 rounded-full flex items-center justify-center mx-auto">
            <Award className="w-10 h-10 text-primary-600" />
          </div>
          <h1 className="text-2xl font-bold mt-4">Assessment Complete!</h1>
          <p className="text-gray-500 mt-1">{result?.test?.title}</p>

          {/* Score progress bar */}
          <div className="mt-6 px-4">
            <div className="flex justify-between text-sm text-gray-500 mb-1">
              <span>0</span>
              <span className="font-semibold text-gray-800 dark:text-gray-200">{pct}%</span>
              <span>{result?.maxScore}</span>
            </div>
            <div className="w-full bg-gray-200 dark:bg-gray-700 rounded-full h-3">
              <div
                className={`${scoreBarColor} h-3 rounded-full transition-all duration-700`}
                style={{ width: `${Math.min(pct, 100)}%` }}
              />
            </div>
          </div>

          <div className="mt-8 grid grid-cols-2 gap-4">
            <div className="p-4 bg-gray-50 dark:bg-gray-800 rounded-xl">
              <p className="text-sm text-gray-500">Total Score</p>
              <p className="text-3xl font-bold text-primary-600">
                {result?.totalScore}/{result?.maxScore}
              </p>
            </div>
            <div className="p-4 bg-gray-50 dark:bg-gray-800 rounded-xl">
              <p className="text-sm text-gray-500">Percentage</p>
              <p className={`text-3xl font-bold ${pct >= 75 ? 'text-green-600' : pct >= 50 ? 'text-amber-600' : 'text-red-600'}`}>
                {pct}%
              </p>
            </div>
            <div className="p-4 bg-gray-50 dark:bg-gray-800 rounded-xl">
              <p className="text-sm text-gray-500">MCQ Score</p>
              <p className="text-xl font-semibold">{result?.mcqScore}</p>
            </div>
            <div className="p-4 bg-gray-50 dark:bg-gray-800 rounded-xl">
              <p className="text-sm text-gray-500">Coding Score</p>
              <p className="text-xl font-semibold">{result?.codingScore}</p>
            </div>
          </div>

          {result?.rank && (
            <div className="mt-6 flex items-center justify-center gap-2 text-lg">
              <Trophy className="w-6 h-6 text-yellow-500" />
              <span>Rank: <strong>#{result.rank}</strong></span>
            </div>
          )}

          {result?.codingAnswers?.length > 0 && (
            <div className="mt-8 text-left">
              <h3 className="font-semibold mb-3">Coding Submissions</h3>
              {result.codingAnswers.map((ca, i) => (
                <div key={i} className="p-3 bg-gray-50 dark:bg-gray-800 rounded-lg mb-2 text-sm">
                  <div className="flex items-center gap-2">
                    {ca.score >= ca.maxScore ? (
                      <CheckCircle2 className="w-4 h-4 text-green-500 shrink-0" />
                    ) : (
                      <XCircle className="w-4 h-4 text-red-400 shrink-0" />
                    )}
                    <p>Question {i + 1} — Score: <strong>{ca.score}/{ca.maxScore}</strong></p>
                  </div>
                  <p className="text-gray-500 ml-6">Language: {ca.language} • Status: {ca.evalStatus}</p>
                  {ca.plagiarismScore > 50 && (
                    <p className="text-red-500 text-xs mt-1 ml-6">⚠ Plagiarism alert: {ca.plagiarismScore}% similarity</p>
                  )}
                </div>
              ))}
            </div>
          )}
        </div>
      </div>
    </Layout>
  );
};

export default TestResult;
